config/routes.rb
Rails.application.routes.draw do
  get 'closest_to_zero_katas/index'
  post 'closest_to_zero_katas/submit_form'
  root 'code_katas#index'
  get 'babysitter_katas/index'
  post 'babysitter_katas/submit_form'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/babysitter_kata.rb
module BabysitterKata
  BEFORE_BEDTIME = 10
  AFTER_BEDTIME = 6
  AFTER_MIDNIGHT = 8

  def self.calculate_earnings(arrival_time, departure_time, bedtime)
    total_amount = 0

    # Can't arrive before 5
    if arrival_time.to_i < 5
      arrival_time = 5
    end

    # Can't stay after 4
    if departure_time.to_i > 4
      departure_time = 4
    end
    # Add the before bedtime amount
    total_amount += (bedtime.to_i - arrival_time.to_i) * BEFORE_BEDTIME

    # Add the after bedtime but before midnight amount
    total_amount += (12 - bedtime.to_i) * AFTER_BEDTIME

    # Add the after midnight amount
    total_amount += departure_time.to_i * AFTER_MIDNIGHT
  end
end

app/models/closest_to_zero_kata.rb
module ClosestToZeroKata
  def self.calculate_closest(numbers)
    # used to keep track of the actual number
    closest_number = numbers.first

    numbers.each do |num|
      if num.to_i.abs < closest_number.to_i.abs
        closest_number = num
      elsif num.to_i.abs == closest_number.to_i.abs
        closest_number = [num.to_i, closest_number.to_i].max
      end
    end

    return closest_number
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/babysitter_katas_controller.rb
class BabysitterKatasController < ApplicationController
  def index
  end

  # TODO: Add error catching when the user submits times before 5:00 pm and after
  # 4:00 am, submits anything other than numbers, etc.
  def submit_form
    @total = BabysitterKata.calculate_earnings(params[:arrival_time], params[:departure_time], params[:bedtime])
    respond_to do |format|
      format.js
    end
  end


end

app/controllers/closest_to_zero_katas_controller.rb
class ClosestToZeroKatasController < ApplicationController
  def index
  end

  def submit_form
    numbers = params[:numbers].split(" ")
    @closest = ClosestToZeroKata.calculate_closest(numbers)
    respond_to do |format|
      format.js
    end
  end
end

app/controllers/code_katas_controller.rb
class CodeKatasController < ApplicationController
  def index
    @hello = 'hello world'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/babysitter_katas_helper.rb
module BabysitterKatasHelper
  
end

app/helpers/closest_to_zero_katas_helper.rb
module ClosestToZeroKatasHelper
end

app/helpers/code_katas_helper.rb
module CodeKatasHelper
end

app/views/babysitter_katas/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <h1>The Babysitter</h1>
      <p>Fill out the fields below. Can't arrive before 5:00 pm or leave after 4:00 am</p>
      <%= form_tag babysitter_katas_submit_form_path, method: :post, class:'col-md-4', remote: true do %>
        <div class="form-group">
          <%= label_tag "Arrival Time" %>
          <%= text_field_tag :arrival_time, nil, class:'form-control', placeholder:'Arrival Time' %>
        </div>
        <div class="form-group">
          <%= label_tag "Departure Time" %>
          <%= text_field_tag :departure_time, nil, class:'form-control', placeholder:'Departure Time' %>
        </div>
        <div class="form-group">
          <%= label_tag "Bedtime" %>
          <%= text_field_tag :bedtime, nil, class:'form-control', placeholder:'Bedtime' %>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      <% end %>
    </div>
    <div class="col-md">
      <h3>The babysitter earned: <span id="calculated-amount-id"></span></h3>
    </div>
  </div>
</div>

app/views/babysitter_katas/submit_form.js.erb
$('#calculated-amount-id').html('$<%= @total %>.00')

app/views/closest_to_zero_katas/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md">
      <h1>Closest To Zero Kata</h1>
      <p>Type a list of numbers delimited by spaces</p>
      <%= form_tag closest_to_zero_katas_submit_form_path, method: :post, class:'col-md-4', remote: true do %>
        <div class="form-group">
          <%= label_tag "Numbers" %>
          <%= text_field_tag :numbers, nil, class:'form-control', placeholder:'Numbers' %>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      <% end %>
    </div>
    <div class="row col-md-5 align-items-center">
      <h3>The closest number to zero is: <span id="closest-number-id"></span></h3>
    </div>
  </div>
</div>

app/views/closest_to_zero_katas/submit_form.js.erb
$('#closest-number-id').html('<%= @closest %>')

app/views/code_katas/index.html.erb
<div class="container align-items-center">
  <div class="col-12 align-items-center">
    <h1>
      Welcome
    </h1>
    <p>
      Thanks for the opportunity. Please use the navigation above to try
      the different katas.
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Amplify Code Kata</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <a class="navbar-brand" href="/">Amplify Code Kata</a>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/babysitter_katas/index">Babysitter <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/closest_to_zero_katas/index">Closet To Zero</a>
          </li>
        </ul>
      </div>
      <div class="pull-right">
        <%= link_to "https://github.com/nmrichards/amplify-code-kata" do %>
          <%= image_tag("github.svg.png", size: "24") %>
        <% end %>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>